CREATE DATABASE IF NOT EXISTS mascota_virtual_app;
USE mascota_virtual_app;


CREATE TABLE TIPOMASCOTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    icono_url VARCHAR(255)
);

CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    contrasena VARCHAR(100) NOT NULL,
    fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DATOSPERSONALES (
    id INT PRIMARY KEY,
    direccion VARCHAR(255),
    telefono VARCHAR(20),
    fecha_nacimiento DATE,
    FOREIGN KEY (id) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE MASCOTAVIRTUAL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    nivel INT DEFAULT 1,
    usuario_id INT NOT NULL,
    tipo_id INT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    FOREIGN KEY (tipo_id) REFERENCES TIPOMASCOTA(id)
);

CREATE TABLE INTERACCION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,
    mascota_id INT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    FOREIGN KEY (mascota_id) REFERENCES MASCOTAVIRTUAL(id) ON DELETE CASCADE
);

CREATE TABLE CHECKLIST (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP,
    usuario_id INT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE META (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(255),
    completada BOOLEAN DEFAULT FALSE,
    checklist_id INT NOT NULL,
    frecuencia_tipo VARCHAR(20) NOT NULL DEFAULT 'daily',
    dias_custom json DEFAULT NULL,
    FOREIGN KEY (checklist_id) REFERENCES CHECKLIST(id) ON DELETE CASCADE
);

CREATE TABLE ALARMA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hora TIME NOT NULL,
    mensaje VARCHAR(255),
    usuario_id INT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE CASCADE
);


